### ISSUE TITLE
启动出错

### ISSUE THREAD

**Issue by 1994** [linuxdeepin/deepin-store#47]
按照README步骤安装启动出错，信息如下：
<class 'Xlib.protocol.request.QueryExtension'>
INFO     Init ui
Traceback (most recent call last):
  File "/usr/bin/deepin-software-center", line 83, in <module>
    start_main()
  File "/usr/bin/deepin-software-center", line 63, in start_main
    software_center.run()
  File "/usr/share/deepin-software-center/ui/software_center.py", line 1132, in run
    self.ready_show()
  File "/usr/share/deepin-software-center/ui/software_center.py", line 878, in ready_show
    self.init_ui()
  File "/usr/share/deepin-software-center/ui/software_center.py", line 833, in init_ui
    self.init_home_page()
  File "/usr/share/deepin-software-center/ui/software_center.py", line 914, in init_home_page
    bus_object = self.system_bus.get_object(DSC_SERVICE_NAME, DSC_SERVICE_PATH)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

**Comment by 1994** [comment]
不好意思，一楼没编辑完不小心发了出去
在运行

```bash
sudo aptitude install python-xappy deepin-storm xdelta3 deepin-software-center-data
```

终端警告：
```bash
Couldn't find package "deepin-storm".  However, the following
packages contain "deepin-storm" in their name:
  python-deepin-storm 
Couldn't find package "deepin-storm".  However, the following
packages contain "deepin-storm" in their name:
  python-deepin-storm 
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 84 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
```

于是我就安装了python-deepin-storm ，不知道是不是和这个依赖有关系
我使用的系统是ubuntu 14,04 LTS，尝试使用PPA安装也是同样的问题存在

```
sudo add-apt-repository ppa:noobslab/deepin-sc
sudo apt-get update
sudo apt-get install deepin-software-center
```

**Comment by greenlaw110** [comment]
我也遇到同样的问题。我的系统是mint 17.1 Rebecca (Cinnamon)，使用PPA安装的：

```
sudo add-apt-repository ppa:noobslab/deepin-sc
sudo apt-get update
sudo apt-get install deepin-software-center
```

**Comment by nickirk** [comment]
现在还是这样，你们有收到开发者的回复吗？

**Comment by q13** [comment]
+1
